title: Вирази обличчя аніме
hero_image: images/banner.png
description: Створи й додай стилі до вебсторінки з уроком малювання аніме.
pdf: resources/rpfi-anime-expression.pdf
meta_title: Вивчай CSS | Навчайся веброзробці | Вирази обличчя аніме
meta_description: Ознайомся з веброзробкою разом із Raspberry Pi Foundation. Вивчай CSS і використовуй стилі для додавання макетів, палітр кольорів і шрифтів до своєї вебсторінки.
version: 4
listed: true
copyedit: true
last_tested: "2022-05-11"
steps:
  - 
    title: Вступ
  - 
    title: Почни створювати вебсторінку
  - 
    title: Додай вираз обличчя
    completion: engaged
  - 
    title: Додай стиль до своєї сторінки
  - 
    title: Стиль із класами
  - 
    title: Кольори та шрифти
    completion: internal
  - 
    title: Поміркуй
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Вдоскональ свій проєкт
