title: Anime expressions
hero_image: images/banner.png
description: anime-expressions description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-11"
steps:
  - title: Introduction
  - title: Start your web page
  - title: Add a facial expression
  - title: Style your page
  - title: Style with classes
  - title: Colours and fonts
  - title: Reflection
  - title: Upgrade your project
  - title: What next?
