title: Expressões do anime
hero_image: images/banner.png
description: Crie e estilize uma página da Web para um tutorial de desenho de anime.
pdf: resources/rpfi-anime-expression.pdf
meta_title: Aprenda CSS | Aprenda desenvolvimento web | Expressões do anime
meta_description: Aprenda desenvolvimento web para iniciantes com a Raspberry Pi Foundation. Aprenda CSS e use estilos para aplicar layouts, paletas de cores e fontes à sua página web.
version: 4
listed: true
copyedit: true
last_tested: "2022-05-11"
steps:
  - 
    title: Introdução
  - 
    title: Comece sua página web
  - 
    title: Adicione uma expressão facial
    completion: engaged
  - 
    title: Estilize sua página
  - 
    title: Estilize com classes
  - 
    title: Cores e fontes
    completion: internal
  - 
    title: Para Refletir
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Atualize seu projeto
