title: Wyrażenia anime
hero_image: images/banner.png
description: Utwórz i wystyluj stronę internetową dla samouczka rysowania anime.
pdf: resources/rpfi-anime-expression.pdf
meta_title: Dowiedz się CSS | Naucz się tworzenia stron | wyrażenia Anime
meta_description: Naucz się tworzenia stron internetowych dla początkujących z Fundacją Raspberry Pi. Naucz się CSS i używaj stylów, aby stosować układy, palety kolorów i czcionki na swojej stronie internetowej.
version: 4
listed: true
copyedit: true
last_tested: "2022-05-11"
steps:
  - 
    title: Wprowadzenie
  - 
    title: Uruchom swoją stronę internetową
  - 
    title: Dodaj wyraz twarzy
    completion: engaged
  - 
    title: Styl swojej strony
  - 
    title: Styl z klasami
  - 
    title: Kolory i czcionki
    completion: internal
  - 
    title: Refleksja
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Ulepsz swój projekt
