title: Espressioni anime
hero_image: images/banner.png
description: Crea e personalizza una pagina web per un tutorial sul disegno di un anime.
meta_title: Impara il CSS | Impara lo sviluppo web | Espressioni anime
meta_description: Impara lo sviluppo web per principianti con Raspberry Pi Foundation. Impara il CSS e usa stili per applicare layout, palette di colori, e font alla tua pagina web.
version: 4
listed: true
copyedit: true
last_tested: "2022-05-11"
steps:
  - 
    title: Introduzione
  - 
    title: Inizia la tua pagina web
  - 
    title: Aggiungi un'espressione facciale
    completion: engaged
  - 
    title: Personalizza la tua pagina
  - 
    title: Personalizza con le classi
  - 
    title: Colori e font
    completion: internal
  - 
    title: Riflessione
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Aggiorna il tuo progetto
